oneChar:
   path: /
   controller: App\Controller\MainController::char

register:
   path: /register
   controller: App\Controller\RegistrationController::register

# article:
#    path: /article/{id}
#    controller: App\Controller\ArticleController::index
#    requirements:
#       id: '\d+'
